spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    mapper:
      accept-case-insensitive-enums: true
#    deserialization:
#      fail-on-unknown-properties: true