apiVersion: apps/v1
kind: Deployment
metadata:
  name: oxygen
  namespace: oxygen
  labels:
    application: oxygen
spec:
  replicas: 3
  selector:
    matchLabels:
      application: oxygen
  template:
    metadata:
      labels:
        application: oxygen
    spec:
      containers:
      - name: oxygen
        image: hello-service:1.0.0
        ports:
        - name: api
          containerPort: 8080
