spring:
  application:
    name: actinium
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.minikube/realms/alchemy
  jackson:
    property-naming-strategy: SNAKE_CASE

scope:
  read: SCOPE_profile