riptide.clients:
  oxygen:
    base-url: http://oxygen.192-168-49-2.nip.io/
    connections:
      connect-timeout: 250 milliseconds
      socket-timeout: 150 milliseconds
      time-to-live: 30 seconds
      max-per-route: 16
#    retry:
#      enabled: true
#      fixed-delay: 50 milliseconds
#      max-retries: 5
#    circuit-breaker:
#      enabled: true
#      failure-threshold: 3 out of 5
#      delay: 30 seconds
#      success-threshold: 5 out of 5
#    caching:
#      enabled: true
#      shared: false
#      max-cache-entries: 1000
#    tracing:
#      enabled: true
#      tags:
#        peer.service: example